name: Build Multi-Arch Docker Image

on: 
  push:
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build and Push
        run: |
          docker buildx create --use --platform=linux/arm64,linux/amd64 --name funnel-builder
          docker buildx build --platform=linux/amd64,linux/arm64 -t ghcr.io/lbeckman314/demonic-server:latest . --push
