# Builds arm64 + amd64 Docker images and pushed to Github's Container Registry
# ref: https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
#
# Manual Build Steps:
# $ docker login ghcr.io --username $USER --password $TOKEN
# $ docker buildx create --use --platform=linux/arm64,linux/amd64 --name builder
# $ docker buildx build --platform=linux/amd64,linux/arm64 -t ghcr.io/$USER/demonic-server:latest . --push

name: Build Multi-Arch Docker Image

on: 
  push:
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/${{ matrix.arch }}

